[package]
name = "rsfm"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19.0"
crossterm = "0.25"
lazy_static = "1.4.0"
infer = "0.3"
rlua = "0.19.4"
levenshtein = "1.0.5"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.6.0"
itertools = "0.10.5"
